# Generated by Django 5.2.4 on 2025-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashLoc',
            fields=[
                ('t_district_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('t_district', models.CharField(blank=True, max_length=255, null=True)),
                ('t_road_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('t_street_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('t_detailed_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('t_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('t_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('t_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('t_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('t_trash_type', models.CharField(blank=True, max_length=50, null=True)),
                ('t_dept', models.CharField(blank=True, max_length=50, null=True)),
                ('t_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('t_date', models.DateField(blank=True, null=True)),
                ('t_update_year', models.IntegerField(blank=True, null=True)),
                ('t_addr', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'trash_loc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('user_reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]