# Generated by Django 5.2.4 on 2025-07-19 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_users_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth',
            field=models.DateField(default=datetime.date(2025, 7, 19)),
            preserve_default=False,
        ),
    ]
