"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
from pymongo import MongoClient
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Django Secret Key
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
#배포할 때 False 여야 함
DEBUG = env.bool('DEBUG', default=False)

# SECURITY: '*'(전체 허용)를 제거하고 환경변수로 허용 호스트를 제한.
# 예) ALLOWED_HOSTS=example.com,15.168.21.218
ALLOWED_HOSTS = env.list(
    'ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1', '15.168.21.218'],
)

AUTH_USER_MODEL = 'common.Users'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    #우리 앱
    'trash_loc',
    'accounts',
    'complain',
    'chatbot',
    'dashboard',
    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# 강제로 로그인 이동후 원래 하던 페이지로 돌아가도록
LOGIN_URL = '/accounts/login/'  # 혹은 이름 기반 URL 사용 시 reverse_lazy로 지정


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database 설정_ sqlite3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


#mongoDB 설정_

load_dotenv()

from mongoengine import connect

# 이미 설정된 환경 변수
MONGO_DB_NAME = "complaints_db"
MONGO_URI = os.getenv("MONGO_URI")

# ✅ MongoEngine 연결 설정 (alias='default' 명시)
connect(
    db=MONGO_DB_NAME,
    host=MONGO_URI,
    alias='default'
)

mongo_client = MongoClient(MONGO_URI)
mongo_db = mongo_client[MONGO_DB_NAME]

#KAKAO API
KAKAO_MAP_KEY = os.getenv("KAKAO_MAP_API_KEY")

# OPENAI API
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 프로젝트 인증 방식으로 토큰 방식 사용
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 배포 시 수정 해야 함.
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 보안 쿠키/전송 설정
# 개발(DEBUG=True)에서는 HTTP로도 동작하도록 완화하고,
# 운영(DEBUG=False)에서는 HTTPS 전용 + 보호 옵션을 강제한다.
SECURE_FLAGS = not DEBUG

CSRF_COOKIE_SECURE = SECURE_FLAGS       # 운영: HTTPS에서만 CSRF 쿠키 전송
SESSION_COOKIE_SECURE = SECURE_FLAGS    # 운영: HTTPS에서만 세션 쿠키 전송
# CSRF 토큰은 프런트 AJAX가 getCookie('csrftoken')로 읽어 X-CSRFToken 헤더에 실으므로
# HttpOnly로 막으면 안 된다. (CSRF 토큰은 세션 비밀이 아님)
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True          # 세션 쿠키는 JS 접근 차단

if SECURE_FLAGS:
    SECURE_SSL_REDIRECT = True                       # HTTP → HTTPS 리다이렉트
    SECURE_HSTS_SECONDS = 31536000                   # 1년 HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # 리버스 프록시(nginx 등) 뒤에서 HTTPS를 종단할 때 필요
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    'http://15.168.21.218:8080',
]
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            # 세션/민감정보가 평문 로그로 남지 않도록 WARNING 이상만 기록
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'standard',
        },
    },
    'loggers': {
        # 우리 앱 로거: 개발(DEBUG=True)에서는 DEBUG, 운영에서는 INFO 이상만 콘솔에 출력
        'accounts': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'chatbot': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'complain': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'dashboard': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'trash_loc': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'django.contrib.sessions': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

INTERNAL_IPS = [
    '127.0.0.1',  # 로컬 환경 에서만 툴바가 뜨도록
]

LOGIN_URL = '/accounts/login/'  # 로그인하지 않았을 때 이동할 로그인 페이지
LOGIN_REDIRECT_URL = '/'  # 로그인 후 이동할 기본 페이지(trash_loc:home)

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",  # Redis 서버 주소
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }